### ISSUE TITLE
ind not defined 

### ISSUE THREAD

**Issue by horaciod** [fredericd/marcjs#10]
during some tests with mrc files I found a bug when there is no indicators (may be the files are corrupted :))

my change  in line 454  or marcjs.js to evaluate the ind var ( in my case is undefined) 
var ind = element[1];
      if (ind != undefined ){
      attr.ind1 = ind.substr(0,1);
      attr.ind2 = ind.substr(1);
      }

**Comment by fredericd** [comment]
Could you attach a sample file to this github issue?

**Comment by horaciod** [comment]
this is the record with the error 
http://bibliotecas.uncu.edu.ar/explorador/Record/OEDSID0005  
Obviously is an error with the indeicator ( a value instead of a number ) but this happend with some of our files. 
MARCXML pasted.
<collection xmlns="http://www.loc.gov/MARC21/slim">
<record>
  <leader>01375Cam#a2200421#a#4500</leader>
  <controlfield tag="001">OEDSID0005</controlfield>
  <controlfield tag="003">OED</controlfield>
  <controlfield tag="005">19990110015819</controlfield>
  <controlfield tag="008">      s2002    ag d   ||m    001 0 spa d</controlfield>

  <datafield tag="020" ind1="a" ind2="9">
    <subfield code="-">4-157103-9</subfield>
  </datafield>

  <datafield tag="082" ind1="0" ind2="4">
    <subfield code="a">011.75</subfield>
    <subfield code="2">20</subfield>
  </datafield>
  <datafield tag="092" ind1=" " ind2=" ">
    <subfield code="s">Sección Tesis</subfield>
    <subfield code="c">T011.75 (T-55)</subfield>
    <subfield code="l">GON</subfield>
  </datafield>
  <datafield tag="100" ind1="1" ind2=" ">
    <subfield code="a">González, Sara Beatriz</subfield>
  </datafield>
  <datafield tag="110" ind1=" " ind2=" ">
  </datafield>
  <datafield tag="245" ind1="1" ind2="3">
    <subfield code="a">El trabajo experimental en la E.G.B. : </subfield>
    <subfield code="b">un instrumento de cambio metodológico / </subfield>
    <subfield code="c">Sara Beatriz González ; [Director de Tesis: Ángel Luis Plastino].</subfield>
  </datafield>
  <datafield tag="260" ind1=" " ind2=" ">
  </datafield>
  <datafield tag="300" ind1=" " ind2=" ">
    <subfield code="a">[6], 1-[107] h. : </subfield>
    <subfield code="b">graf. col. ; </subfield>
    <subfield code="c">30 cm.</subfield>
  </datafield>
  <datafield tag="440" ind1=" " ind2=" ">
  </datafield>
  <datafield tag="502" ind1=" " ind2=" ">
    <subfield code="a">Tesis (Maestría) -- Facultad de Educación Elemental y Especial, Universidad Nacional de Cuyo ; Universidad de Alcalá, 2002.</subfield>
  </datafield>
  <datafield tag="650" ind1=" " ind2="7">
    <subfield code="a">EDUCACIÓN</subfield>
    <subfield code="2">unescot</subfield>
  </datafield>
  <datafield tag="650" ind1=" " ind2="7">
    <subfield code="a">INVESTIGACIÓN</subfield>
    <subfield code="2">unescot</subfield>
  </datafield>
  <datafield tag="650" ind1=" " ind2="7">
    <subfield code="a">CIENCIAS</subfield>
    <subfield code="2">unescot</subfield>
  </datafield>
  <datafield tag="650" ind1=" " ind2="7">
    <subfield code="a">FÍSICA</subfield>
    <subfield code="2">unescot</subfield>
  </datafield>
  <datafield tag="650" ind1=" " ind2="7">
    <subfield code="a">MÉTODOS DE INVESTIGACIÓN</subfield>
    <subfield code="2">unescot</subfield>
  </datafield>
  <datafield tag="650" ind1=" " ind2="7">
    <subfield code="a">MÉTODOS EXPERIMENTALES</subfield>
    <subfield code="2">unescot</subfield>
  </datafield>
  <datafield tag="650" ind1=" " ind2="7">
    <subfield code="a">MÉTODOS DE ENSEÑANZA</subfield>
    <subfield code="2">unescot</subfield>
  </datafield>
  <datafield tag="650" ind1=" " ind2="7">
    <subfield code="a">ESTUDIOS DE CASOS</subfield>
    <subfield code="2">unescot</subfield>
  </datafield>
  <datafield tag="650" ind1=" " ind2="7">
    <subfield code="a">ENCUESTAS</subfield>
    <subfield code="2">unescot</subfield>
  </datafield>
  <datafield tag="650" ind1=" " ind2="7">
    <subfield code="a">ANÁLISIS DE DATOS</subfield>
    <subfield code="2">unescot</subfield>
  </datafield>
  <datafield tag="653" ind1=" " ind2=" ">
    <subfield code="a">ENTREVISTAS</subfield>
  </datafield>
  <datafield tag="653" ind1=" " ind2=" ">
    <subfield code="a">TRABAJO EXPERIMENTAL</subfield>
  </datafield>
  <datafield tag="653" ind1=" " ind2=" ">
    <subfield code="a">PROTOCOLO DE OBSERVACIÓN</subfield>
  </datafield>
  <datafield tag="700" ind1="1" ind2=" ">
    <subfield code="a">Plastino, Ángel Luis, </subfield>
    <subfield code="e">dir..</subfield>
  </datafield>
  <datafield tag="908" ind1=" " ind2=" ">
  </datafield>
  <datafield tag="908" ind1=" " ind2=" ">
    <subfield code="a">imp</subfield>
  </datafield>
  <datafield tag="929" ind1=" " ind2=" ">
    <subfield code="a">DON</subfield>
  </datafield>
  <datafield tag="930" ind1=" " ind2=" ">
    <subfield code="a">8853</subfield>
    <subfield code="d">res</subfield>
  </datafield>
  <datafield tag="999" ind1=" " ind2=" ">
    <subfield code="a">mab</subfield>
  </datafield>
</record>
</collection>

**Comment by fredericd** [comment]
Apparently, you encountered this error by parsing a MARCXML file. Do you have an xml file containing a record with this empty indicator? For me, it could be considered as a non-error, since it means that you input xml file is malformed.

**Comment by horaciod** [comment]
I'm parsing a BIG ISO file.
yes, the record is malformed because allow a "A" letter in indicator
position.
Maybe I need to validate the iso with another tool previously.
Thanks for the support.




Lic. Horacio Degiorgi
http://bdigital.uncu.edu.ar
http://sid.uncu.edu.ar
Mendoza - Argentina
