### ISSUE TITLE
while loop blocking nextTick

### ISSUE THREAD

**Issue by ghost** [fredericd/marcjs#12]
Hi,
Thank you for your very useful library, I have been using this internally for a while but I am experiencing a problem with the latest version.

The rewritten Iso2709Reader in 0.1.12 relies on a while loop which is blocking nextTick, even your example code now fails to update its counter when running on 0.1.12.

Chris

**Comment by fredericd** [comment]
What node.js version are you using?

**Comment by chcommunico** [comment]
v0.10.41 on this box

**Comment by fredericd** [comment]
You should upgrade, and if your error's still here, details un test plan.

**Comment by chcommunico** [comment]
Hi, thank you for your reply.

I have also tested on v4.2.4 and other versions but the problem isn't really a bug, its just the way node works.

in 0.1.10 Iso2709Reader read in the stream and when it has enough data for a record it emitted that back out for processing.

In 0.1.12 the whole file is read into a variable and then that data is looped over in a while(){} loop. All the time that while loop is running node will not go to nextTick so no other tasks can complete until the loop has finished running.

An easy example of this is to run your sample code but with a big enough marc file to see the problem. The setInterval will only run before Iso2709Reader hits the while loop, and then again after. setInterval can't run all the time the loop is active.

```
var count=0;
var reader = new marc.Iso2709Reader(fs.createReadStream('largemarcfile.mrc'));
reader.on('data', function(record) {
	count++;
});
var intervalId = setInterval(function() { console.log(reader.count); }, 1000);

reader.on('end', function(){
	clearInterval(intervalId);
	console.log('done', count, reader.count);
});
```

Running this code would output something like:

```
0
0
0
0
done 374528 374528
```
