### ISSUE TITLE
Can't process a large ISO 2709 file

### ISSUE THREAD

**Issue by SydneyUniLibrary-Jim** [fredericd/marcjs#19]
I need to process an ISO 2709 file larger than 2GB.

If I run `bin/marcjs -p iso2709 very-large-file.mrc` I get an error being thrown.

```
buffer.js:182
    throw err;
    ^

RangeError: "size" argument must not be larger than 2147483647
    at Function.Buffer.allocUnsafe (buffer.js:209:3)
    at Function.Buffer.concat (buffer.js:401:23)
    at ReadStream.<anonymous> (/Users/jim/Documents/Development/git-hub-repos/marcjs/lib/marcjs.js:93:19)
    at emitNone (events.js:110:20)
    at ReadStream.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

If I'm reading the code correctly, this is because Iso2709Reader is collecting all the chunks from the incoming stream into the array `this.data` and then only starting to parse the array when the incoming stream ends.

I'd like to change it so that Iso2709Reader only collects enough chunks for the incoming stream in order to reach the end of a record, processes that record and emits a 'data' event, and only then continuing to collect more chunks.

To achieve this, I propose to:

- Introduce a new function called `this.processData`. This function will parse as many whole records as there are in the chunks of `this.data`, calling `this.parse` to parse each record, and emitting a "data" event for each record. The function leaves any left over data as the sole chunk in `this.data`.
- Change `stream.on('data', …)` to push the chunk on the `this.data` and then call `this.processData`.
- Change `stream.on('end', …)` to push the last chunk (if there is one) and then call `this.processData`.

I've forked the repository and will code the changes there before submitting a pull request for this issue.

I think this might also address issue #12.

**Comment by fredericd** [comment]
How large is your file? Thanks for coming with a solution. There must be something wrong here:

https://github.com/fredericd/marcjs/blob/master/lib/marcjs.js#L86-L126

The code was supposed to *emit* records as soon as possible, without buffering. So this is definitely a bug, and even for small files, since the module was designed to pipe data between in/ou stream.

**Comment by SydneyUniLibrary-Jim** [comment]
4.6GiB. 😊 

BTW: What's your policy on the minimum supported version of NodeJS? The package.json file says NodeJS 0.6.x. Is that still the case?

**Comment by fredericd** [comment]
I can't say. I haven't personally touch this package since a while. I was about to ask for a copy of you file, but 4.6G, not thanks :-)

**Comment by SydneyUniLibrary-Jim** [comment]
Personally I'm using Node v8. But how about if I code against Node v4, which is the last version just being maintained.

Would it be okay if I update the versions of the dependencies as well?

**Comment by fredericd** [comment]
Yes, please do itn thanks. This library can't be maintained (not by myself in any case) for several Nodejs version. I agree to target latest current version: v8.

**Comment by fredericd** [comment]
Do you know well Nodejs Stream library?

Reading the code, I can see that something is wrong the way the read stream is managed. We should use readable.pause() / readable.resume() to pause and resume reading when the buffer is too big. That is the way to go...

**Comment by SydneyUniLibrary-Jim** [comment]
Here's where I'm at (before I call it a night).

I've added a test like this:

```javascript
var dummyInput = new stream.PassThrough();
var reader = new m.Iso2709Reader(dummyInput);
var recordsRead = [];
var ended = false;
reader.on('data', function(rec) { console.log('. reader emitted data'); recordsRead.push(rec) });
reader.on('end', function() { console.log('. reader emitted end'); ended = true });

recordsRead.should.have.lengthOf(0);
ended.should.be.false();
console.log('> pumping record #0 into input stream');
dummyInput.write(marcRecords[0]);
console.log('< done pumping record #0 into input stream');
//recordsRead.should.have.lengthOf(1);
//ended.should.be.false();
console.log('> pumping record #1 into input stream');
dummyInput.write(marcRecords[1]);
console.log('< done pumping record #1 into input stream');
//recordsRead.should.have.lengthOf(2);
//ended.should.be.false();
console.log('> pumping record #2 into input stream, with end');
dummyInput.end(marcRecords[2]);
console.log('< done pumping record #2 into input stream, with end');
recordsRead.should.have.lengthOf(3);
ended.should.be.true();
```

(I've commented out the tests between the writes because they fail at the moment.)

And I added a `console.log` to the start and end of Iso2709Reader's `stream.on('data', …)` and `stream.on('end', …)`.

When I run the test, I get output like.

```
> pumping record #0 into input stream
>> start stream.on('data', …)
<< end stream.on('data', …)
< done pumping record #0 into input stream
> pumping record #1 into input stream
>> start stream.on('data', …)
<< end stream.on('data', …)
< done pumping record #1 into input stream
> pumping record #2 into input stream, with end
>> start stream.on('data', …)
<< end stream.on('data', …)
< done pumping record #2 into input stream, with end
>> start stream.on('end', …)
. reader emitted data
. reader emitted data
. reader emitted data
. reader emitted end
<< end stream.on('end', …)
```

So it is only when we enter `stream.on('end', …)` that we start parsing the records.

If I commented out `dummyInput.end(marcRecords[2]);` in the test, then I get no data events being emitted from the reader at all. This makes some sense because without ending the input stream, the code in `stream.on('end', …)` never runs.

I think this highlights the the core of the issue for my situation.  That is parsing on happens in `stream.on('end', …)` and never in `stream.on('data', …)`.


I think pausing the input stream will cause starvation of the reader. Pausing the input stream won't cause it emitted an 'end' event.

**Comment by SydneyUniLibrary-Jim** [comment]
FYI. The actual test is a more complex that what I've put above because of async.

I haven't pushed the test into GitHub yet. But a copy of the test is at https://gist.github.com/SydneyUniLibrary-Jim/81a927bd6e8449f07150c834b3ea4dcb

**Comment by SydneyUniLibrary-Jim** [comment]
After implementing incremental reading for ISO2709Reader, I was able to process my 4.6 GiB using no more than 127MiB of memory.

**Comment by fredericd** [comment]
The new version of the library solves your issue. It uses properly nodejs streams.

**Comment by SydneyUniLibrary-Jim** [comment]
Create to see some further work on this library. I guess this means I can abandon my nascent work on [marc-transformed](https://github.com/SydneyUniLibrary-Jim/marc-transformed).

**Comment by fredericd** [comment]
Nice work! What is your usage of JS MARC library? Would you share about your needs? I'd be interested in investigating whether 'marcjs' can do the job, or have to be extended to be of more generic usage.

**Comment by SydneyUniLibrary-Jim** [comment]
Normally around applying big, systematic transformations to the bib and authority records in our library system.

Usual workflow is a long the lines of:

1. Export a bunch of records from the system (or almost all of them, as I need to do when I opened this ticket)
1. Read the records from a file, apply a transformation to them one by one, write them to another file.
1. Import the records, overlaying the original records in the system.

I don't think this is anything marcjs cannot do, especially now with it's duplex stream API.

**Comment by fredericd** [comment]
Seeing your code on fixing 880 fields, I can imagine doing it this way:

```javascript
const fs   = require('fs'),
      MARC = require('../lib/marcjs');

const infile = 'myisofile.mrc';
const outfile = 'fixedfile.xml';
const readable = MARC.stream(fs.createReadStream(infile), 'Iso2709');
const writable = MARC.stream(fs.createWriteStream(outfile), 'Marcxml');
const fix880 = MARC.transform( record => {
	let fields = record.get('880');
	// Do something on 880 fields
});
writable.pipe(fixbiblio).pipe(writable);
```
A lot of 'cool' things could be done also with promises, and await/async JS ECMA2015. Don't hesitate to ask for sample code if you need.
