### ISSUE TITLE
Usage example in readme.md not working correctly

### ISSUE THREAD

**Issue by matt2martin** [fredericd/marcjs#25]
Hello,

In the readme.md, the usage example doesn't make use of the transform you set-up, so the script as is won't append the 801 fields to the input records .

Changing:
```
reader.on('data', record => {
  writers.forEach(writer => writer.write(record) );
});
```

To: 
```
reader.on('data', record => {
  trans.write(record);
  record = trans.read(record);
  writers.forEach(writer => writer.write(record) );
});
```

Makes the code work and it is how you have structured the calls in your test/test.js file.

Cheers,
Matt

**Comment by fredericd** [comment]
Thanks for catching and reporting! Would you modify the README yourself and make a pull request?

**Comment by matt2martin** [comment]
I have done the pull request.
