### ISSUE TITLE
How to format the separator characters?

### ISSUE THREAD

**Issue by PhilAndrew** [fredericd/marcjs#36]
If I want to have the ; and / and other separator characters should I add them to the end of the string of the field?

When I output as text it came out as

`300 ## $a 148 pages ; $b coloured illustrations, coloured maps, coloured portraits  ; $c 30 cm`

This is not entirely correct, ; $b should not have a space, it should be ;$b

**Comment by fredericd** [comment]
When you say that it "comes out", what do you mean exactly? How do you get this result?

**Comment by PhilAndrew** [comment]
If I do

```
record.append(['650', '#0', 'a .', 'z', 'there'])
const result = Marc.format(record, 'Text')
```

Then I get

`650 #0 $a hello . $z there`

However I expect I should get the following since the separators should be close to the $ sign with no space

`650 #0 $a hello .$z there`

**Comment by PhilAndrew** [comment]
Let me close this, it doesn't really seem to be an issue.

**Comment by fredericd** [comment]
Thanks for your feedback.
