### ISSUE TITLE
Load an mrc file record fails with a record from Libraries Australia

### ISSUE THREAD

**Issue by PhilAndrew** [fredericd/marcjs#37]
I have a Marc record file I obtained from https://librariesaustralia.nla.gov.au/search/advancedSearch

Clicked Download and selected "MARC (Unicode)", obtained a .mrc file.

Using the following code it was unable to parse the file, it did not give an error but the output looks wrong.

```
var what = require('marcjs');
var Marc = what.Marc;
fs.readFile('record.mrc', 'utf8', function(err, data) {
  if (err) throw err;
  const p = Marc.parse(data, 'iso2709');
  console.log(Marc.format(p, 'Marcxml'));
});
```

As opposed to using this library, with this library the output is correct, obtained from here
https://github.com/afronkin/node-marcrecord

```
var marcrecord = require("marcrecord");
const util = require('util');

var marcReader = new marcrecord.MarcIsoReader();
marcReader.openSync('record.mrc');
//console.log(marcRecord);
while (record = marcReader.nextSync()) {
console.log(util.inspect(record, false, null, true ));
  //var field = record.getVariableField('200');
}

marcReader.closeSync();
```

Here is the mrc file attached

[record.mrc.txt](https://github.com/fredericd/marcjs/files/7266352/record.mrc.txt)
.

**Comment by fredericd** [comment]
The proper usage is rather something like that:

```javascript
const { Marc } = require('marcjs');
const fs = require('fs');

let reader = Marc.stream(fs.createReadStream('pathto/record.mrc'), 'Iso2709');

reader.on('data', (record) => {
  console.log(record.as('Marcxml'));
});
```

I can show you how exactly to use the module depending on your needs.

**Comment by fredericd** [comment]
Our outputing in text, using "pipe" :

```javascript
const { Marc } = require('../lib/Marc');
const fs = require('fs');

let reader = Marc.stream(fs.createReadStream('/home/tamil/record.mrc'), 'Iso2709');
let trans = Marc.transform((record) => {
  console.log(record.as('Text'));
});
reader.pipe(trans);

**Comment by PhilAndrew** [comment]
Thanks, your method worked, is there a way to do this without the stream? If I have the data in memory in a string.
Right now I'm thinking to look at a way to convert a string to a stream.

**Comment by PhilAndrew** [comment]
I was able to achieve the outcome I wanted with string to stream to take my string of data and your method above.

https://www.npmjs.com/package/string-to-stream

**Comment by fredericd** [comment]
You can parse an ISO2709 string this way:

```javascript
const { Marc, Iso2709 } = require('marcjs');

const iso2709string = 'xxx';
const record = Iso2709.parse(iso2709string);
console.log(record.as('Text'));
```

**Comment by PhilAndrew** [comment]
Thanks!
