### ISSUE TITLE
encoding

### ISSUE THREAD

**Issue by andrisi** [fredericd/marcjs#38]
Please document how to handle different encodings in reading and displaying files. It seems that UTF8 formatted files come out somehow converted to unreadable chars with the defaults. Thanks.

**Comment by fredericd** [comment]
**marcjs** is designed to work with utf8 encoded file. What kind of file doesn't work for you? Do you have a sample? If you have non-utf8 ISO2709 files, there are other tools that could be used to convert them into utf8, and the you can use marcjs to transform them and convert them into other formats.

**Comment by andrisi** [comment]
Thanks for getting back to me. It is an utf8 file indeed and it's probably an issue with the Windows Terminal app I'm using to run it on Windows 10. On Ubuntu it reads the same file ok.

**Comment by andrisi** [comment]
Silly me... I should have added this issue to marc4js. I had the issue there, and then switched to your tool. Sorry.

**Comment by fredericd** [comment]
Thanks for you feedback. Glad to see this library does the job for you.
