### ISSUE TITLE
Trouble creating ISO2709 from scratch

### ISSUE THREAD

**Issue by jjg** [fredericd/marcjs#8]
I'm a MARC neophyte so I may be overlooking something obvious, but I'm having trouble creating a new ISO2709 file from scratch.

Here's the code I'm using to create a sample file:
````
var marc = require("marcjs");
var fs = require("fs");

var marc_output = new marc.Iso2709Writer(fs.createWriteStream("album_0.mrc"));
var record = new marc.Record;
record.append([ '998', '  ', 'a', 'Demians', 'b', 'Frédéric']);

marc_output.write(record);
marc_output.end();

````

Here's the code I'm using to parse the output file created by the above code:
````
var marc = require("marcjs");
var fs = require("fs");

// read .mrc file and dump the contents to the console 
console.log("___BEGIN___");

var reader = new marc.Iso2709Reader(fs.createReadStream("album_0.mrc"));

reader.on("data", function(record){
    console.log(record.fields);
});

reader.on("end", function(){
    console.log("___END___");
});
````

Here's the output I get when parsing the output of the first script:
````
___BEGIN___

buffer.js:416
      return this.parent.utf8Slice(start, end);
                         ^
TypeError: Bad argument.
    at Buffer.toString (buffer.js:416:26)
    at parse (/home/jason/Development/musicat-api/node_modules/marcjs/lib/marcjs.js:45:24)
    at ReadStream.<anonymous> (/home/jason/Development/musicat-api/node_modules/marcjs/lib/marcjs.js:110:24)
    at ReadStream.emit (events.js:117:20)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at ReadStream.Readable.push (_stream_readable.js:128:10)
    at onread (fs.js:1575:12)
    at Object.wrapper [as oncomplete] (fs.js:466:17)
````

If I use the same parsing code above on an .mrc file I received from the library, it parses and displays the expected output.  

I didn't see an example of creating an ISO2709 file from scratch (only parsing and appending to an existing one).  Are there additional initialization steps necessary, or additional mandatory MARC records that need to be appended before the `Iso2709Reader()` can parse the file?

**Comment by fredericd** [comment]
Nothing obvious, indeed. You code is clean. But a valid leader is missing. Creating a new record, a valid leader is not created. You could add:

**Comment by jjg** [comment]
Happy to help, thanks for the fix!

Is 0.1.10 available via NPM?

**Comment by jjg** [comment]
Found it, looks great; thanks @fredericd !

**Comment by fredericd** [comment]
You found it yourself so. Bye.
